spring:
  cache:
    type: HAZELCAST
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost/upgrade?currentSchema=campsite
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 5
      leak-detection-threshold: 60000
      idle-timeout: 30000
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        id:
          new_generator_mappings: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          hazelcast:
            native_client_address: 127.0.0.1
            native_client_group: dev
            use_native_client: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
    show-sql: false
    open-in-view: true


  #liquibase:
  #  change-log: classpath:/database/migrations/changelog.xml
  #  default-schema: mis
  #  enabled: true
  #  contexts: none
  application:
    name: campsite
  sql:
    init:
      mode: always
logging:
  level:
    .: info
    org:
      springframework:
        boot: warn
        web: warn
    org.hibernate.SQL: warn

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'
      buffered: false
      prefix: stdout
      directory: logs
    basedir: tomcat
    threads:
      min-spare: 50
  servlet:
    context-path: /reservation
  port: 8087

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: health, info, loggers
        exclude: env, beans